# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'YMPayHandlerDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YMPayHandlerDemo
  pod 'UMengSocialCOM', '~> 5.2.1'
  pod 'AFNetworking', ‘~> 3.1.0’
end
